return function(t)
    local Util = require("shared.util")
    t:describe("util")
    t:eq(Util.itemKey("a"), "a", "itemKey no nbt")
    t:eq(Util.itemKey("a", "hash"), "a#hash", "itemKey with nbt")
    t:ok(Util.deepEqual({ a = 1, b = { 2, 3 } }, { a = 1, b = { 2, 3 } }), "deepEqual same")
    t:ok(not Util.deepEqual({ a = 1 }, { a = 1, b = 2 }), "deepEqual extra key")
    t:ok(not Util.deepEqual({ a = 1, b = 2 }, { a = 1 }), "deepEqual missing key")
    t:eq(Util.count({ a = 1, b = 2 }), 2, "count")
    t:eq(Util.clamp(5, 0, 3), 3, "clamp hi")
    t:eq(Util.clamp(-1, 0, 3), 0, "clamp lo")
    t:eq(Util.formatCount(1500), "1.5k", "formatCount k")
    t:eq(Util.formatCount(999), "999", "formatCount small")
    t:eq(Util.formatCount(2500000), "2.5M", "formatCount M")
    t:eq(Util.formatRate(0), "+0.0", "formatRate zero")
    t:eq(Util.formatRate(-3), "-3.0", "formatRate neg")
end
